---
- hosts: local

  vars:
    board: "nice_nano_v2"
    shield: "corne"
    clear_cache: false
    zephyr_version: "3.2"
    log_dir: "/tmp"
    docker_config_dir: "/workspace/zmk-config"
    docker_zmk_dir: "/workspace/zmk"
    host_config_dir: "/Users/dsn/projects/zmk/zmk-config"
    host_zmk_dir: "/Users/dsn/projects/zmk/zmk"
    output_dir: "/Users/dsn/projects/zmk/zmk-config/out"
    docker_image: "zmkfirmware/zmk-dev-arm:{{ zephyr_version }}"

  tasks:
    - name: "zmk | Create container from {{ docker_image }}"
      community.docker.docker_container:
        name: "zmk-dev"
        image: { { docker_image } }
        volumes:
          - "{{ host_zmk_dir }}:{{ docker_zmk_dir }}"
          - "{{ host_config_dir }}:{{ docker_config_dir }}"
          - "zmk-root-user-{{ zephyr_version }}:/root"
          - "zmk-zephyr-{{ zephyr_version }}:{{ docker_zmk_dir }}/zephyr"
          - "zmk-zephyr-tools-{{ zephyr_version }}:{{ docker_zmk_dir }}/tools"
          - "zmk-zephyr-modules-{{ zephyr_version }}:{{ docker_zmk_dir }}/modules"
